GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/12345

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "tg_id": "123456",
    "tg_username": "dev_test",
    "tg_avatar_url": "https://example.com/avatar.jpg",
    "fio": "Иванов Иван",
    "gender": "male",
    "phone": "79999999999",
    "birthday": "01.01.1990"
}

###

DELETE http://localhost:3000/api/users/123456

###

PATCH http://localhost:3000/api/users/approve/12345

###

POST http://localhost:3000/api/games
Content-Type: application/json

{
    "name": "Тренировка в Юбилейном 2",
    "location": "СП Юбилейный",
    "address": "пр. Ленина 203",
    "date": "12.02.2026",
    "time": "20:00",
    "duration": "120",
    "description": "Низкий уровень сложности",
    "price": "200",    
    "maxPlayers": "14"      
}

###

GET http://localhost:3000/api/games/7

###

GET http://localhost:3000/api/games/

###

PUT http://localhost:3000/api/games/2
Content-Type: application/json

{
    "name": "Тренировка в Юбилейном 3",
    "location_name": "СП Юбилейный",
    "location_address": "пр.Ленина 203",
    "start_datetime": "2024-02-13T19:00:00",
    "duration": "120"
}

###

DELETE http://localhost:3000/api/games/16

###

GET http://localhost:3000/api/games/6/players

###

POST http://localhost:3000/api/games/7/join
Content-Type: application/json

{
    "user_id": "14"
}

###

POST http://localhost:3000/api/games/7/leave
Content-Type: application/json

{
    "user_id": "14"
}

###

POST http://localhost:3000/api/games/7/promote
Content-Type: application/json

{
    "user_id": "14"
}

###

POST http://localhost:3000/api/users/guest
Content-Type: application/json

{
    "fio": "Гость"
}