### USERS - begin

GET http://localhost:3000/api/users
x-debug-mode: 1

###

GET http://localhost:3000/api/users/12345
x-debug-mode: 1

###
POST http://localhost:3000/api/users
x-debug-mode: 1
Content-Type: application/json

{
    "tg_id": "123460",
    "tg_username": "dev_test5",
    "tg_avatar_url": "https://example.com/avatar.jpg",
    "fio": "Иванов Иван",
    "gender": "male",
    "phone": "79999999999",
    "birthday": "01.01.1990"
}

###

DELETE http://localhost:3000/api/users/123456
x-debug-mode: 1

###

PATCH http://localhost:3000/api/users/approve/12345
x-debug-mode: 1

### USERS - end

### GAMES - begin

POST http://localhost:3000/api/games
x-debug-mode: 1
Content-Type: application/json

{
    "name": "Тренировка в Юбилейном 14",
    "location": "СП Юбилейный",
    "address": "пр. Ленина 203",
    "date": "18.02.2026",
    "time": "20:00",
    "duration": "120",
    "description": "Низкий уровень сложности",
    "price": "200",    
    "maxPlayers": "14"      
}

###

GET http://localhost:3000/api/games/7
x-debug-mode: 1

###

GET http://localhost:3000/api/games/
x-debug-mode: 1

###

PUT http://localhost:3000/api/games/2
x-debug-mode: 1
Content-Type: application/json

{
    "name": "Тренировка в Юбилейном 3",
    "location_name": "СП Юбилейный",
    "location_address": "пр.Ленина 203",
    "start_datetime": "2024-02-13T19:00:00",
    "duration": "120"
}

###

DELETE http://localhost:3000/api/games/16
x-debug-mode: 1

###

GET http://localhost:3000/api/games/6/players
x-debug-mode: 1

###

POST http://localhost:3000/api/games/7/join
x-debug-mode: 1
Content-Type: application/json

{
    "user_id": "14"
}

###

POST http://localhost:3000/api/games/7/leave
x-debug-mode: 1
Content-Type: application/json

{
    "user_id": "14"
}

###

POST http://localhost:3000/api/games/7/promote
x-debug-mode: 1
Content-Type: application/json

{
    "user_id": "14"
}

###

POST http://localhost:3000/api/users/guest
x-debug-mode: 1
Content-Type: application/json

{
    "fio": "Гость"
}

### GAMES - end

### TEMPLATES - begin

POST http://localhost:3000/api/templates
x-debug-mode: 1
Content-Type: application/json

{
    "name": "Тренировка в Юбилейном 14",
    "location": "СП Юбилейный",
    "address": "пр. Ленина 203",
    "date": "",
    "time": "20:00",
    "duration": "120",
    "description": "Низкий уровень сложности",
    "price": "200",    
    "maxPlayers": "14"      
}

###

GET http://localhost:3000/api/templates
x-debug-mode: 1

###

GET http://localhost:3000/api/templates/2
x-debug-mode: 1

###

DELETE http://localhost:3000/api/templates/2
x-debug-mode: 1

###

PUT http://localhost:3000/api/templates/3
x-debug-mode: 1
Content-Type: application/json

{
    "name": "Тренировка в Юбилейном 14",
    "location_name": "СП Юбилейный",
    "location_address": "пр. Ленина 203",
    "date": "",
    "time": "21:00",
    "duration": 120,
    "description": "Низкий уровень сложности",
    "price": 200,
    "max_players": 14
}

### TEMPLATES - end\

### NEW - begin

POST http://localhost:3000/api/news
x-debug-mode: 1
Content-Type: application/json

{
    "title": "Первая новость 2",
    "content": "Ура! У нас теперь есть новости!"
}

###

GET http://localhost:3000/api/news
x-debug-mode: 1

###

GET http://localhost:3000/api/news/2
x-debug-mode: 1

###

DELETE http://localhost:3000/api/news/2
x-debug-mode: 1

###

PUT http://localhost:3000/api/news/1
x-debug-mode: 1
Content-Type: application/json

{
    "title": "Первая новость 2222",
    "content": "Ура! У нас теперь есть новости!"
}

### NEW - end

### Загрузка изображения
POST http://localhost:3000/api/upload
x-debug-mode: 1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="volleyball.jpg"
Content-Type: image/jpeg

< c:\Users\User\Downloads\vvl_bot_logo_small.png
--WebAppBoundary--

###

GET http://localhost:3000/uploads/volleyball.jpg
x-debug-mode: 1

###

DELETE http://localhost:3000/api/upload/volleyball.jpg
x-debug-mode: 1